baseurl = "/"
languageCode = "en-us"
paginate = 5
theme = "hello-friend"

[params]
contentTypeName = "posts"
defaultTheme = "dark"
showMenuItems = 2
showReadingTime = false

[languages]
[languages.en]
copyright = ""
dateFormatList = "02-01-2006"
dateFormatSingle = "02-01-2006"
keywords = ""
menuMore = "Show More"
minuteReadingTime = "min read"
newerPosts = "Newer posts"
olderPosts = "Older posts"
readMore = "Read more"
readOtherPosts = "Read other posts"
subtitle = "a simple about / blog / portfolio site"
title = "ssentinull"
writtenBy = "Written by"

[languages.en.params.logo]
logoHomeLink = "/"
logoText = "ssentinull"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
